version: "2"

services:
  php:
    container_name: openloyalty_backend
    image: swr.ap-southeast-2.myhuaweicloud.com/nimblehq/nimble-cx-demo-fpm
    build:
      context: '../'
      dockerfile: './docker/prod/php/fpm-dockerfile'
    links:
      - db
      - elk
      - mail
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - frontend_customer_panel_url=http://demo.local:8183/client
      - frontend_password_reset_url=demo.local:8183/client#!/password/reset
  nginx:
    container_name: openloyalty_frontend
    image: swr.ap-southeast-2.myhuaweicloud.com/nimblehq/nimble-cx-demo-web
    build:
      context: '../'
      dockerfile: './docker/prod/web/app-dockerfile'
    links:
      - php
    ports:
      - "80:80"
      - "8182:3001"
      - "8183:3002"
      - "8184:3003"
    command: bash -c "sed -i -e 's@"http://openloyalty.localhost/api"@'\"http://demo.local/api\"'@g' /var/www/openloyalty/front/config.js && nginx -g 'daemon off;'"
  elk:
    container_name: openloyalty_elk
    image: swr.ap-southeast-2.myhuaweicloud.com/nimblehq/nimble-cx-demo-elasticsearch:2.2
    build:
      context: '../'
      dockerfile: './docker/base/elasticsearch-dockerfile'
  db:
    container_name: openloyalty_db
    image: postgres:9
    env_file:
        - .env
  mail:
    container_name: openloyalty_mail
    image: mailhog/mailhog
    ports:
      - "8186:8025"
